export * from "./auth.interface";
export * from "./detail-information.interface";
export * from "./file-data.interface";
export * from "./file.interface"
export * from "./friend.interface";
export * from "./message.interface"
export * from "./room.interface"
export * from "./sended-friend.interface";
export * from "./notification.interface";